<?php

namespace AppBundle\Repository;

/**
 * ShippingRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShippingRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
