# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        # encode users coming from db entity
        AppBundle\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

        in_memory:
            memory:
                users:
                    admin:
                        #admin123
                        password: $2y$12$iz1KliHdMUQpzcE6EbWmTemrXyMC40pOVJkmDlXlbpOvwh.psLAly
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/company
            http_basic: ~
            provider: our_db_provider

        admin:
            pattern: ^/user
            http_basic: ~
            provider: in_memory

    access_control:
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/company, roles: ROLE_USER }
